apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mediawiki.fullname" . }}
  labels:
    app: {{ include "mediawiki.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mediawiki.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mediawiki.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MEDIAWIKI_DB_HOST
              value: "mediawiki-db"
            - name: MEDIAWIKI_DB_USER
              value: "{{ .Values.mediawikiUsername }}"
            - name: MEDIAWIKI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediawiki-db
                  key: password
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: mediawiki-data
              mountPath: /var/www/html/images
      volumes:
        - name: mediawiki-data
          persistentVolumeClaim:
            claimName: {{ include "mediawiki.fullname" . }}-pvc
