apiVersion: v1
kind: Secret
metadata:
  name: mediawiki-db
type: kubernetes.io/kubernetes.io/basic-auth
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  password: "{{ .Values.mediawikiPassword }}"
